package com.tm2score.entity.user;



import java.io.Serializable;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.NamedQueries;
import jakarta.persistence.NamedQuery;
import jakarta.persistence.Table;
import jakarta.persistence.Transient;


@Entity
@Table( name = "orgtraits" )
@NamedQueries( {
        @NamedQuery( name = "OrgTraits.findByOrgId", query = "SELECT o FROM OrgTraits AS o WHERE o.orgId=:orgId")        
} )
public class OrgTraits implements Serializable
{
    @Transient
    private static final long serialVersionUID = 1L;


    @Id
    @GeneratedValue( strategy = GenerationType.IDENTITY )
    @Column( name = "orgtraitsid" )
    private int orgTraitsId;

    @Column( name = "orgid" )
    private int orgId;
        
    @Column( name = "localestr" )
    private String localeStr;

    /*
     Text summary of the orgTraits. Can be initially generated by AI
    */
    @Column( name = "summary" )
    private String summary;

    
    @Column( name = "plaintext" )
    private String plainText;

    public int getOrgTraitsId() {
        return orgTraitsId;
    }

    public void setOrgTraitsId(int orgTraitsId) {
        this.orgTraitsId = orgTraitsId;
    }

    public int getOrgId() {
        return orgId;
    }

    public void setOrgId(int orgId) {
        this.orgId = orgId;
    }

    public String getLocaleStr() {
        return localeStr;
    }

    public void setLocaleStr(String localeStr) {
        this.localeStr = localeStr;
    }

    public String getSummary() {
        return summary;
    }

    public void setSummary(String summary) {
        this.summary = summary;
    }

    public String getPlainText() {
        return plainText;
    }

    public void setPlainText(String plainText) {
        this.plainText = plainText;
    }

    
}
